### ISSUE TITLE
Chapter 4: Incorrect number of linear regions in `Figure 4.1` and `Figure 4.5`? 

### ISSUE THREAD

**Issue by chaoz-dev** [udlbook/udlbook#120]
Please correct me if I misread or misunderstood the following content and figures in Chapter 4:

1. `Equation 4.1-4.4` and `Figure 4.1a` depict two shallow networks composed together, where each shallow network contains one hidden layer with three hidden units each. The corresponding `Figure 4.1b` and `Figure 4.1c`, which depict the first and second composed networks respectively, show three linear regions. However, should these figure not show _four_ linear regions instead, as three hidden units imply three "joints", and therefore four linear regions? 
1a. Similarly, should `Figure 4.1d` not show 10 linear regions as a result of nine "joints" due to the composition of the two shallow networks? (This would also match the pattern described in `Figure 4.2` for two network inputs) 
1b. If these are errata, then the caption for `Figure 4.1` will require amendment, as well as the text before `Figure 4.2` describing the composed network's number of linear regions. 
2. The same questions arise for `Figure 4.5` for the deep network with two hidden layers of three hidden units each (presumably the same rules apply with respect to joints and linear regions). 

Assuming that no drop out has occurred on a hidden unit, a possible explanation is that two different linear regions line up; ie. all linear regions are represented, but one of the "joints" is straight.

**Comment by vonrafael** [comment]
It may be the case that the choice of parameters helped to limit the number of linear regions to 3, 
You're right about the _[d hidden unit --> (d+1) linear regions]_ as  discussed in chapter 3
Moving along  with the  same logic as stated by you, like in fig 4.1a, the correct way of doing things has been depicted in the exercise, i.e.  **[d hidden unit --> (d+1) linear regions]** as in figure **4.8a-b** and the preceding logic seems to be a fit there!!! So 
Go take a look at it too!!!!!

**Comment by udlbook** [comment]
The reason is that although you can create four linear regions with three hidden units, you cannot create four linear regions with independent slopes (i.e., the fourth region is either flat, or some combination of the other three).  To see this, consider, that each of the linear regions has a slope that is a combination of slopes associated with the three hidden units.  So there are only really "three" atomic slopes.

Because I want to emphasize the most general case, I'm assuming for these figures that there is also a "joint" at x=0 and that the slope of the function to the left of that is zero.   That allows the remaining linear regions to have independent slopes.

Perhaps I should write this somewhere, but I always feel that by the time that people ask this question, they basically know what is going on anyway.

**Comment by chaoz-dev** [comment]
Understood. Thanks for the clarification!
