### ISSUE TITLE
12.3.1 permutation equivariant or invariant?

### ISSUE THREAD

**Issue by pieris98** [udlbook/udlbook#131]
Dear Prof. Prince,

On the 24_12_2023 version, page 227 Section 12.3.1 Positional encoding you mention "More precisely, it is *equivariant* with respsect to input permutations". I was a bit confused after also reading this slideshow online:
https://people.tamu.edu/~sji/classes/attn-slides.pdf
Slides 13-15 provide a theorem and proof for Equivariance of vanilla self-attention ($A_s$) vs. Invariance of self-attention with a learned query ($A_Q$). 

I'm wondering which one is the case with the dot-product self-attention defined in the chapter's previous sections.

Shedding any light from you or the community would be much appreciated.

**Comment by udlbook** [comment]
Hi Pieris,

My statement and the architecture I describe corresponds to the standard
self-attention mechanism, which is the equivariance proof they provide.

The invariance proof they provide is for a non-standard variant of the
self-attention mechanism, where the query is learned rather than depending
on the data.   Basically, if you change the mechanism a bit,  you can make
it invariant to permutations.

Hope that this helps,

Simon
