### ISSUE TITLE
Small indexing typo in UDL-Book,  formula B.18

### ISSUE THREAD

**Issue by GitMalk** [udlbook/udlbook#137]
Small indexing typo in UDL-Book,  formula B.18
![image](https://github.com/udlbook/udlbook/assets/119065393/6d4280bb-4ce7-48c7-9d3f-ad44e367082c)

**Comment by udlbook** [comment]
Well spotted!  How annoying, I should have spotted that.   It will be fixed in the next online version and when the book is reprinted (probably in about a year).  If you send me your name to the email address on the front of the book draft, I will add you to the acknowledgements.   Let me know if you find anything else!
