### ISSUE TITLE
Typo in Equation 14.2 and 14.3

### ISSUE THREAD

**Issue by ywang-aads** [udlbook/udlbook#166]
In both the text:
> More precisely, it returns the exponential of the expected KL-divergence between $Pr(y_i|\mathbf{x}_i^\ast )$ and $Pr(y)$

and in Eq. 14.2 and 14.3, it should be $Pr(y | \mathbf{x}_i^\ast)$, not $Pr(y_i | \mathbf{x}_i^\ast)$. 

This way both the KL-divergence and $Pr(y)$ in 14.3 as an expectation over the generated image set can make sense:  $Pr(y) = \frac{1}{I} \sum\limits_{i=1}^I Pr(y | \mathbf{x}_i^\ast).$

**Comment by ywang-aads** [comment]
New Edits 10/7/24:

Hi Simon,

To clarify my previous comment, there are two key points regarding the Inception Score description in Section 14.3:

The probability $$Pr(y | \mathbf{x}_i^\ast)$$ should only be indexed by the generated image $\mathbf{x}_i^\ast$. Indexing the class label $y$ by $i$ (i.e., using $$Pr(y_i | \mathbf{x}_i^\ast)$$) is confusing because the class distribution is still over the variable $y$, and the dependence of the specific image index $i$ is only via $\mathbf{x}_i^\ast$. The correct notation reflects that $y$ is not tied to any particular image index.

Similarly, the KL-divergence and the marginal distribution $Pr(y)$ in Eq. 14.3, as an expectation over the generated image set, should use consistent notation. For example, the consistent notations in Equation 14.3 should be:
$$Pr(y) = \frac{1}{I} \sum\limits_{i=1}^I Pr(y | \mathbf{x}_i^\ast).$$

This expression represents the empirical marginal class distribution of $y$ over all generated images ${x_i^\ast }$. The distinction is important to ensure that the expectation is computed across the generated images, not indexed class labels.

I hope this clarifies my earlier point. Thanks for considering this correction!

**Comment by udlbook** [comment]
Hi Yuanhang,

As you probably noticed, I left this without either accepting or rejecting
it, basically because I wasn't sure what to do.   Now you have clarified
this, I can see that you are right.   I should have gotten in touch with
you ages ago.

I've fixed it and I've added your name to the acknowledgments.  You will
see it next time that the book is updated online and when it is reprinted
(probably next year some time).

Thanks so much for engaging with this;  please let me know if you find
anything else.

Simon
