### ISSUE TITLE
Question on chapter 10 equation 10.3 page 163 - convolution equivariant to translation

### ISSUE THREAD

**Issue by total-expectation** [udlbook/udlbook#176]
Hi Prince,

Really like the book so far! It's very much straight to the point and clear most of the time with good explanations.
Now to my question, I'm sure I'm misunderstanding something here, but on chapter 10 equation 10.3 page 163, you claim that the convoloution operator is equivariant w.r.t to translation. So I thought I should test it with a simple example.  Given this definition of equivariance

$$f[t[x]] = t[f[x]]$$

I apply it here on my example. Let t(x) be a translation function and f(x) the dot product between the filter weights (I know this isn't a convolution operator, but it should still replicate what the convolution would do for one step of the convolution process) and three elements from the input data x. Then we have
```math
\begin{align}
    t(x) &= x + c \\
    f(x) &= wx \\
    f[t[x]] &= f(x+c) = w(x+c) = wx + wc \\
    t[f[x]] &= t(wx) = wx + c \\
    wx + c &\neq wx + wc \iff f[t[x]] \neq t[f[x]]
\end{align}
```

where $c \in \mathbb{R}^3$, $x \in \mathbb{R}^3$, $w = [w_1, w_2, w_3]^T$. Note that $x \in \mathbb{R}^n$, but I simplify it here just to focus on 3 elements in it to make the vector addition compatible. As you can see from the last equation f is not equivariant even though c is a translation vector on x. So I'm wondering where I'm going wrong here?

Thanks in advance!

**Comment by dsuedholt** [comment]
It can be a bit confusing that CNNs typically perform cross-correlation and call it convolution anyway, but the dot product is something categorically different. That difference leads to a problem in your example: $wx + c$ with $w, c, x\in\mathbb{R}^3$ doesn't make sense, you're adding a scalar ($wx$) to a vector ($c$).

It's easier to think in terms of signals: consider a 1D signal $x$ and a kernel $h$. Then the convolution operation is $$(x\ast h)[n] = \sum_{k=-\infty}^\infty x[k]h[n-k]$$
Notice that the result of the convolution is **again a signal**, not a scalar.

To show translation equivariance, consider a shift operator $S_c(x[n]) = x[n - c]$. Using the index transformation $k = k' - c$, we see that

$$\begin{align}S_c\left((x\ast h)[n]\right) &= S_c\left(\sum_{k=-\infty}^\infty x[k]h[n - k]\right)\\
&= \sum_{k=-\infty}^\infty x[k]h[n - c - k]\\ 
&= \sum_{k'=-\infty}^\infty x[k' - c]h[n - k']\\
&= \sum_{k'=-\infty}^\infty S_c\left(x[k']\right)h[n - k'] = (S_c(x)\ast h)[n]
\end{align}$$

So if $f(x)$ is the convolution with some kernel, $f$ is equivariant under shifting the input since $f(S_c(x)) = S_c(f(x))$.

**Comment by total-expectation** [comment]
Thank you for a quick response! If possible I have a few follow-up questions, since I haven't taken a signal processing course before, so treating things as a signal is not something familiar to me, so sorry for asking dumb questions.

1. What is a 1D signal in this case? Is it just an array of values in $\mathbb{R}$?
2. What is happening between $x[k]h[n-k]$? Is it just a dot product being applied for each k and then you sum it all up over all k? Or is it an elementwise multiplication, in which case I can understand then why it remains a signal even after the summation.
3. If it is however a dot product, shouldn't the result of $\sum_{k=-\infty}^{\infty} be a scalar? Although It's infinity so I guess that maybe has something to do with it?$

Sorry for asking very basic questions.

Thanks in advance!

**Comment by total-expectation** [comment]
One follow-up question. The bounds of the summation goes to infinity in both directions. But images and filters often have finite bounds. Does the conclusion you gave still hold for finite bounds?

**Comment by udlbook** [comment]
Thanks so much @dsuedholt for a very clear explanation!  @total-expectation, you are correct, that this runs into problems at the edges of the (finite) image.   So in the real world, the operations is "approximately" equivariant.
