### ISSUE TITLE
 3.1.1 Neural network intuition - independent regions

### ISSUE THREAD

**Issue by jinto** [udlbook/udlbook#215]
"However, only three of the slopes of these regions are independent; the fourth is either zero (if all the hidden units are inactive in this region) Problem 3.9or is a sum of slopes from the other regions."

It seems only the first region is independent of others.
- first region : theta31
- second region: theta11+theta31
- third region: theta11+theta21+theta31
- forth region: theta11+theta21

However, I might have misunderstood something.

**Comment by udlbook** [comment]
Hi Jay,

I think this is a misunderstanding of what is meant by "independent".  The
second region is independent of the first because you can get any value
regardless of theta31 by changing theta11.    Likewise you can get any
value for the third region given the first two by changing theta21.
 However, the fourth region is predetermined (i.e. not independent) because
we have already chosen theta11 and theta21.  This would happen whatever
order you choose the sections in.

Simon
