### ISSUE TITLE
There is lower loss value in the section 2_1_Supervised_Learning

### ISSUE THREAD

**Issue by betinkaraman** [udlbook/udlbook#221]
I found lower loss value than lowest loss value in the book.
![Screenshot 2024-08-12 203640](https://github.com/user-attachments/assets/79a9987c-4cf9-479d-9656-8a4a88180606)

**Comment by udlbook** [comment]
Hi!

Thanks so much for writing. I agree.  It might be because I rounded some of
the data point values to make it neater for the notebook.  Anyway, I have
changed the figure now so that it agrees with the notebook.  You'll see the
change when I next update the online version and when the book is reprinted
(probably in about a year).  If you send your full name to the e-mail
address on the front of the PDF, I'd be really happy to add your name to
the acknowledgements.

Let me know if you find anything else!

Simon
