### ISSUE TITLE
Confused about maximum log-likelihood

### ISSUE THREAD

**Issue by Wuaner** [udlbook/udlbook#235]
I can not understand the deduction  process of Maximum likelihood  under Chapter 5. Loss functions. Is there any math materials can help me to understand it better?

**Comment by udlbook** [comment]
Hey -- I don't really know of any other better resources, but feel free to
e-mail me with specific questions at the e-mail address on the front of the
pdf.  It usually helps if people explain their current understanding and
then I can point out what is wrong or confused.  This is useful for me as
well, because if I can figure out what you are having trouble with, I can
improve the explanation for the second edition.

S.

**Comment by Wuaner** [comment]
Its just I do not have too much math and statistics background so it's hard for me to understood the math-related materials. b
But this book is definitely amazing, thanks you so much for generous offering it publicly.

**Comment by udlbook** [comment]
Yeah.  There's no real avoiding learning some linear algebra and some
probability.  Try to find a course in each and work through the problems.
It is time well spent as these two areas of mathematics are used widely in
many different areas.

Simon

**Comment by Wuaner** [comment]
Yeah, You are so correct, Simon.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
