### ISSUE TITLE
Typo in Lab 7.2 Indicator_Function?

### ISSUE THREAD

**Issue by c-x-g** [udlbook/udlbook#240]
I think there may be a typo in the [indicator function in lab 7.2](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap07/7_2_Backpropagation.ipynb)
  x_in[x_in>=0] = 1
  x_in[x_in<0] = 0

```
def indicator_function(x):
  x_in = np.array(x)
  x_in[x_in>=0] = 1
  x_in[x_in<0] = 0
  return x_in
```

If I am not mistaken, the block above should have the conditions
  x_in[x_in>0] = 1
  x_in[x_in<=0] = 0

so the final code should look like:
```
def indicator_function(x):
  x_in = np.array(x)
  x_in[x_in>0] = 1
  x_in[x_in<=0] = 0
  return x_in
```

Please correct me if I am wrong thank you!

**Comment by udlbook** [comment]
Hi Carl,

Thank you so much for getting in touch.  I apologize for taking so long to
reply.

I agree and I've fixed it.  It probably doesn't matter much, because it's
very unlikely that the input will ever be exactly zero, but it's definitely
better your way.

Thanks again, and let me know if you see anything else.

Simon
