### ISSUE TITLE
Answer booklet for students, Problem 15.4, Jenson-Shannon divergence, possible mistake

### ISSUE THREAD

**Issue by aleksandrskoselevs** [udlbook/udlbook#242]
The answer says:
> The Jenson-Shannon divergence is infinite when a ≤ −1 or a ≥ 1 and takes the value a log[2] + (1 − a) log[1] otherwise.

However, for a ≤ −1 we get a different answer:

$$
\begin{aligned}
\text{JS}(P \| Q) 
&= \frac{1}{2} \int_{-\infty}^{\infty} P(z) \log\left( \frac{P(z)}{\frac{P(z) + Q(z)}{2}} \right) dz + \frac{1}{2} \int_{-\infty}^{\infty} Q(z) \log\left( \frac{Q(z)}{\frac{P(z) + Q(z)}{2}} \right) dz \\
&= \frac{1}{2} \int_{0}^{1} 1 \times \log\left( \frac{1}{\frac{1 + 0}{2}} \right) dz + \frac{1}{2} \int_{a}^{a+1} 1 \times \log\left( \frac{1}{\frac{1 + 0}{2}} \right) dz \\
&= \frac{1}{2} \int_{0}^{1} \log(2) \, dz + \frac{1}{2} \int_{a}^{a+1} \log(2) \, dz \\
&= \frac{1}{2} \times \log(2) \times (1 - 0) + \frac{1}{2} \times \log(2) \times \left( (a + 1) - a \right) \\
&= \frac{1}{2} \times \log(2) \times 1 + \frac{1}{2} \times \log(2) \times 1 \\
&= \frac{1}{2} \log(2) + \frac{1}{2} \log(2) \\
&= \log(2) \quad \text{for } a \leq -1
\end{aligned}
$$

, which would be equivalent for a ≥ 1.

**Comment by udlbook** [comment]
Hi there,

Thanks so much for getting in touch. You are right -- the answer is wrong.
I took a quick look at it, and I think the correct answer is:

The Jenson-Shannon divergence is $\log 2$ when $a\leq-1$ or $a\geq 1$ and
takes the value $|a|\log[2]$ otherwise

This makes sense as the JS divergence is zero when the distributions
overlap and it moves smoothly to the log 2 value as they separate, becoming
zero after they are disjoint.

Let me know if you disagree!

Simon

**Comment by aleksandrskoselevs** [comment]
Hi Simon,

Yes, I agree with $|a|\log[2]$

Thank you,

Aleks
