### ISSUE TITLE
Question about Diffusion Reverse Process Notation (Section 18.3) - Version October 1, 2024

### ISSUE THREAD

**Issue by altaykacan** [udlbook/udlbook#252]
Hello,

Thank you so much for writing this book, it is immensely helpful in my deep learning journey!!

I was studying the VAE and diffusion model chapters and am a little bit confused with the notation. In the VAE, $q(z|\theta)$ is the distribution parametrized by the encoder and is the variational approximation for the true posterior $Pr(z|x)$ .

However, for diffusion models we describe the (true) forward process with $q(z_t | z_{t-1})$ instead of $Pr(z_t|z_{t-1})$ as mentioned in the footnote in page 350 to match the VAE notation.

**Isn't this actually the opposite of the VAE notation?**

 As far as I understand, for diffusion models we use $Pr(z_{t-1}|z_t, \phi_t)$ as the approximations of the true reverse distributions in page 355 (please see image below). However, for VAE's the distribution denoted with $q$ is the approximation and the one with $Pr$ is the true distribution as per page 335.

I'd think that representing the approximations with $p(\cdot)$ instead of $Pr(\cdot)$ would be correct here but I am not sure. My intuition is that for latent variable models we assume we have one *true* distribution $Pr(x, z_1, z_2, ..., z_T)$ (with $q$ instead of $Pr$ following the notation in chapter 18). We then marginalize out the latent variables to get the true data distribution $Pr(x)$. That's why using the same symbol for the approximations and the true distribution for diffusion models is confusing to me.

I'd appreciate any clarification or help. I know this is a long question but I hope I could explain my confusion clearly!

![image](https://github.com/user-attachments/assets/b027d17e-3395-4a19-9267-828851bd18e9)

**Comment by udlbook** [comment]
Hi there!

You are correct -- in the diffusion model, the q(.) represent
the predetermined encoding stages and the Pr() distributions represent the
learned decoding stages.  So, we are learning the decoder, so that it
matches the predetermined approximation to its posterior.   In comparison,
in the VAE< we are learning both.

I agree that this all a bit weird and backwards, but I think the notation
is at least consistent with the VAE chapter, even if it is not 100%
intuitive.  When I write the next version of this book, I think this
chapter will completely change.  It was all very new when I wrote this
(October 2022), but there is a lot more work now and better connections
with other areas.  I'll store this e-mail and see if I can improve things
at that time.

Simon
