### ISSUE TITLE
Possible typo in equation 5.31 (dx instead of dy)

### ISSUE THREAD

**Issue by RoyAmoyal** [udlbook/udlbook#3]
Hey, it's Roy the undergraduate student from your previous LinkedIn post. 

I think there is a typo (dx instead of dy) in equation 5.31 but I may be wrong.

![image](https://user-images.githubusercontent.com/69425073/193700019-db5d9afc-e8b1-4b89-9b0a-6685088a6b1c.png)

And I would like to ask a small question, how did we get from the first expression in the equation to the second expression?

Thanks!

**Comment by udlbook** [comment]
It is a typo.  Well spotted.  The integral in the first line disappears because the delta functions each have mass one and are centred on the data points. There is zero probability mass between them and so when the product is integrated, only the positions of the data points remain.  Does that make sense?  I'll try to update the draft to reflect this -- if you are confused, then other people probably will be as well.  Thanks!

**Comment by RoyAmoyal** [comment]
> It is a typo. Well spotted. The integral in the first line disappears because the delta functions each have mass one and are centred on the data points. There is zero probability mass between them and so when the product is integrated, only the positions of the data points remain. Does that make sense? I'll try to update the draft to reflect this -- if you are confused, then other people probably will be as well. Thanks!

Thanks for the explanation!
