### ISSUE TITLE
Chapter 15: formula 15.8

### ISSUE THREAD

**Issue by where2go947** [udlbook/udlbook#82]
First, thanks for your great learning material!
I'm a new learner, who would like to learn GAN.
![loss function]

I was confused about 2 points:
- why should the optimal discriminator take the value of `formula 15.7`? How to understand it?
- I think ![sig1] is right, but ![sig2] instead (Green part). Could you please explain it?

Thanks in advance!

[loss function]: https://i.stack.imgur.com/lHfp6.png

[sig1]: https://chart.googleapis.com/chart?cht=tx&chl=sig%5Bf%5Bx%5E*%2C%20%5Cphi%20%5D%5D%3D%5Cfrac%7BPr(x%5E*)%7D%7BPr(x%5E*)%20%2B%20Pr(x)%7D
[sig2]: https://chart.googleapis.com/chart?cht=tx&chl=sig%5Bf%5Bx%5E*%2C%20%5Cphi%20%5D%5D%3D%5Cfrac%7BPr(x)%7D%7BPr(x%5E*)%20%2B%20Pr(x)%7D

**Comment by udlbook** [comment]
Hi, apologies for the long delay in replying.  The fraction you are referring too is actually derived from Bayes' rule with uniform priors:

Pr(is_real| x) = Pr(x|is_real)Pr(is_real)/ (Pr(x|is_real)Pr(is_real) + Pr(x|isn't_real)Pr(isn't_real))

where we have assumed that Pr(is_real)=Pr(isn't real) = 0.5.

The equations are correct since this is now the optimal discriminator.  I agree that this notation kind of sucks, and if you can think of a cleaner way to explain it, then let me know and I'll try to integrate into the next version.
